function RequestIplAsync(iplName)
	RequestIpl(iplName)
	Citizen.Wait(0)
end

function RemoveIplAsync(iplName)
	RemoveIpl(iplName)
	Citizen.Wait(0)
end

Citizen.CreateThread(function()
	-- Casino
	RequestIplAsync("vw_casino_main")
	RequestIplAsync("hei_dlc_casino_aircon")
	RequestIplAsync("hei_dlc_casino_aircon_lod")
	RequestIplAsync("hei_dlc_casino_door")
	RequestIplAsync("hei_dlc_casino_door_lod")
	RequestIplAsync("hei_dlc_vw_roofdoors_locked")
	RequestIplAsync("hei_dlc_windows_casino")
	RequestIplAsync("hei_dlc_windows_casino_lod")
	RequestIplAsync("vw_ch3_additions")
	RequestIplAsync("vw_ch3_additions_long_0")
	RequestIplAsync("vw_ch3_additions_strm_0")
	RequestIplAsync("vw_dlc_casino_door")
	RequestIplAsync("vw_dlc_casino_door_lod")
	RequestIplAsync("vw_casino_billboard")
	RequestIplAsync("vw_casino_billboard_lod(1)")
	RequestIplAsync("vw_casino_billboard_lod")
	RequestIplAsync("vw_int_placement_vw")
	RefreshInterior(275201)
		
	-- Casino Garage
	RequestIplAsync("vw_casino_garage")
	RequestIplAsync("vw_casino_carpark")

	-- Casino Penthouse
	RequestIplAsync("vw_casino_penthouse")
	RequestIplAsync("vw_dlc_casino_apart")
	PinInteriorInMemory(274689)
	RefreshInterior(274689)

	ActivateInteriorEntitySet(274689, "casino_manager_default")
	ActivateInteriorEntitySet(274689, "Set_Pent_Tint_Shell")
	SetInteriorEntitySetColor(274689, "Set_Pent_Tint_Shell", 2)
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_spax_shell")
	SetInteriorEntitySetColor(274689, "vw_vwint02_pent_spax_shell", 2)
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_spa_shell")
	SetInteriorEntitySetColor(274689, "vw_vwint02_pent_spa_shell", 0)
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_sbt_shell")
	SetInteriorEntitySetColor(274689, "vw_vwint02_pent_sbt_shell", 0)
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_mbt_shell")
	SetInteriorEntitySetColor(274689, "vw_vwint02_pent_mbt_shell", 0)
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_hal_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_mb_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_lou_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_sb_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_din_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_bar_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_off_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_lv_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_ex_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_spax_window")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_spa_window")

	ActivateInteriorEntitySet(274689, "Set_Pent_Pattern_01")
	SetInteriorEntitySetColor(274689, "Set_Pent_Pattern_01", 1)

	ActivateInteriorEntitySet(274689, "Set_Pent_Spa_Bar_Open")
	ActivateInteriorEntitySet(274689, "Set_Pent_Media_Bar_Open")
	ActivateInteriorEntitySet(274689, "Set_Pent_NoDealer")
	ActivateInteriorEntitySet(274689, "Set_Pent_Arcade_Modern")
	ActivateInteriorEntitySet(274689, "Set_Pent_Bar_Clutter")
	ActivateInteriorEntitySet(274689, "set_pent_bar_light_0")
	ActivateInteriorEntitySet(274689, "set_pent_bar_party_0")

	ActivateInteriorEntitySet(274689, "prop_tv_flat_03b")
	ActivateInteriorEntitySet(274689, "prop_tv_flat_michael")
	ActivateInteriorEntitySet(274689, "prop_tv_flat_01")
	ActivateInteriorEntitySet(274689, "vw_prop_vw_cinema_tv_01")
	ActivateInteriorEntitySet(274689, "v_res_tt_tvremote")
	ActivateInteriorEntitySet(274689, "vw_prop_vw_tv_rt_01a")

	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_mbt_mirror")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_mbx_drframe")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_loux_mirror")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_sbt_mirror")
	ActivateInteriorEntitySet(274689, "vw_vwint02_pent_wk_mirror") 
end)
